### ISSUE TITLE
Recent version has problems with SMS text

### ISSUE THREAD

**Issue by JavaJens** [hauckwill/linconnect-client#17]
After the recent update the text from incoming SMS is not displayed anymore.
The source (name+photo) and application (via SMS/MMS) is correctly displayed, but not the content.

**Comment by hauckwill** [comment]
Version 2.20? Which version of Android are you running?

**Comment by JavaJens** [comment]
Sorry it took so long. The issue was on my other phone.
I have version 2.21 of LinConnect running on  Cyanogenmod 11 (Android 4.4.4), so it might have to do with the custom ROM.
Anyway, here is the error log, thanks for this wonderful application!

```02-14 12:57:02.190: W/Bundle(2048): Key android.text expected String but value was a android.text.SpannableString.  The default value <null> was returned.
02-14 12:57:02.315: W/Bundle(2048): Attempt to cast generated internal exception:
02-14 12:57:02.315: W/Bundle(2048): java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
02-14 12:57:02.315: W/Bundle(2048): 	at android.os.Bundle.getString(Bundle.java:1121)
02-14 12:57:02.315: W/Bundle(2048): 	at com.willhauck.linconnectclient.NotificationUtilities.getNotificationText(NotificationUtilities.java:177)
02-14 12:57:02.315: W/Bundle(2048): 	at com.willhauck.linconnectclient.NotificationUtilities.sendData(NotificationUtilities.java:71)
02-14 12:57:02.315: W/Bundle(2048): 	at com.willhauck.linconnectclient.NotificationService.onNotificationPosted(NotificationService.java:32)
02-14 12:57:02.315: W/Bundle(2048): 	at android.service.notification.NotificationListenerService$INotificationListenerWrapper.onNotificationPosted(NotificationListenerService.java:168)
02-14 12:57:02.315: W/Bundle(2048): 	at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:56)
02-14 12:57:02.315: W/Bundle(2048): 	at android.os.Binder.execTransact(Binder.java:404)
02-14 12:57:02.315: W/Bundle(2048): 	at dalvik.system.NativeStart.run(Native Method)
02-14 12:57:02.322: W/Bundle(2048): Key android.text expected String but value was a android.text.SpannableString.  The default value <null> was returned.
02-14 12:57:02.408: W/Bundle(2048): Attempt to cast generated internal exception:
02-14 12:57:02.408: W/Bundle(2048): java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
02-14 12:57:02.408: W/Bundle(2048): 	at android.os.Bundle.getString(Bundle.java:1121)
02-14 12:57:02.408: W/Bundle(2048): 	at com.willhauck.linconnectclient.NotificationUtilities.getNotificationText(NotificationUtilities.java:177)
02-14 12:57:02.408: W/Bundle(2048): 	at com.willhauck.linconnectclient.NotificationUtilities.sendData(NotificationUtilities.java:71)
02-14 12:57:02.408: W/Bundle(2048): 	at com.willhauck.linconnectclient.OldNotificationService$NotifyTask.doInBackground(OldNotificationService.java:50)
02-14 12:57:02.408: W/Bundle(2048): 	at com.willhauck.linconnectclient.OldNotificationService$NotifyTask.doInBackground(OldNotificationService.java:47)
02-14 12:57:02.408: W/Bundle(2048): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-14 12:57:02.408: W/Bundle(2048): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-14 12:57:02.408: W/Bundle(2048): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-14 12:57:02.408: W/Bundle(2048): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-14 12:57:02.408: W/Bundle(2048): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-14 12:57:02.408: W/Bundle(2048): 	at java.lang.Thread.run(Thread.java:841)```
